apiVersion: v1
kind: Service
metadata:
  name: scclient-service
  namespace: edaapp
spec:
  type: NodePort
  selector:
    app: scclient
  ports:
    - name: http-port
      protocol: TCP
      port: 8184
      targetPort: 8184
      nodePort: 30921